service: test
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-1
functions:
  pokemonFindAll:
    handler: ./src/handlers/pokemonHandler.findAll
    events:
      - http:
          path: /
          method: get
  pokemonFindOne:
    handler: ./src/handlers/pokemonHandler.findOne
    events:
      - http:
          path: /{pokemonId}
          method: get
plugins:
  - serverless-offline