service: test
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-1
functions:
  pokemon:
    handler: ./src/handlers/pokemonHandler.pokemon
    events:
      - http:
          path: /
          method: get
plugins:
  - serverless-offline